const nodemailer = require("nodemailer");
require("dotenv").config();
const email = data => {
  let transporter = nodemailer.createTransport({
    host: "smtp.gmail.com",
    port: 465,
    secure: true,
    logger: true,
    auth: {
      user: process.env.P_EMAIL,
      pass: process.env.PASSWORD
    }
  });
  let mailOptions = {
    from: `Personal Site: ${data.name},  <${data.email}>`, //sender
    to: process.env.P_EMAIL, //list receivers
    subject: `Portfolio ${data.name} contacted you!`,
    text: `${data.message} -- ${data.email}`
  };
  let ccOptions = {
    from: `Austin Loveless, <${process.env.P_EMAIL}>`, //sender
    to: data.email, //list receivers
    subject: "Thanks for reaching out!",
    text: `Hey ${data.name},
    I will get back to you as soon as I can - thank you again for reaching out!
    - Austin Loveless
(This message has been autogenerated - feel free to reach me at ${
      process.env.P_EMAIL
    })`
  };
  transporter.sendMail(mailOptions);
  transporter.sendMail(ccOptions);
  return null;
};

module.exports = {
  email
};
